export const eventsData = [
  {
    id: '1',
    icon: '🎮',
    title: 'FIFA Night',
    host: { name: 'Amine', age: 26, avatar: '🙋‍♂️' },
    location: 'Game Center',
    when: '9:30 Tomorrow',
    description: 'Looking for chill person to join us on a FIFA 26, and be ready to lose haha...',
    distance: '1km away',
  },
  {
    id: '2',
    icon: '🍺',
    title: 'Afterwork drinks',
    host: { name: 'Imad', age: 32, avatar: '🤷‍♂️' },
    location: 'Zing Rabat',
    when: '20:00 Today',
    description: 'Hey nearkers! I\'m always thirsty after work and looking for some company. You\'re all welco...',
    distance: '4km away',
  },
  {
    id: '3',
    icon: '👫',
    title: 'Beach Walk',
    host: { name: 'Amina', age: 23, avatar: '🙋‍♀️' },
    location: 'Beachside Promenade',
    when: '18:00 Today',
    description: 'Hey nearkers! i\'m looking for a person. You\'re all...',
    distance: '6km away',
  },
];